---
repository:
  name: kleister-docs
  description: "Kleister: Documentation"
  homepage: https://kleister.eu
  topics: kleister, minecraft, docs, documentation, hugo

  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false

  default_branch: master

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

  allow_update_branch: true
  allow_auto_merge: true
  delete_branch_on_merge: true

...
