version: '{build}'
image: 'Visual Studio 2017'

clone_folder: 'c:\go\src\github.com\kleister\kleister-docs'

environment:
  DOCKER_USERNAME:
    secure: '4YzzahbEiMZQJpOCOd1LAw=='
  DOCKER_PASSWORD:
    secure: 'VqO/G3Zfslu6zSLdwHKO+Q=='

install:
  - ps: |
      Install-Product node ''
  - cmd: |
      choco install make
      choco install hugo
  - cmd: |
      docker version
      go version
build_script:
  - cmd: |
      npm install
      npm run build
  - cmd: |
      make build

      docker pull microsoft/nanoserver:10.0.14393.1593
      docker build -f Dockerfile.windows -t kleister/kleister-docs:windows .
test_script:
  - cmd: |
      docker run --rm kleister/kleister-docs:windows caddy.exe -version
deploy_script:
  - ps: |
      $ErrorActionPreference = 'Stop';
      if ( $env:APPVEYOR_PULL_REQUEST_NUMBER -Or ! $env:APPVEYOR_REPO_BRANCH.Equals("master")) {
        Write-Host Nothing to deploy.
      } else {
        docker login --username $env:DOCKER_USERNAME --password $env:DOCKER_PASSWORD
        docker push kleister/kleister-docs:windows
      }

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/6820ca0e69546e16ee90
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
