workspace:
  path: src

pipeline:
  build:
    image: webhippie/hugo:latest
    commands:
      - make build

  docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: kleister/kleister-docs
    tags: [ '${TAG}' ]
    when:
      event: tag
      branch: refs/tags/*

  docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: kleister/kleister-docs
    tags: [ 'latest' ]
    when:
      event: push
      branch: master

  gitter:
    image: plugins/gitter
    secrets: [ gitter_webhook ]
